### ISSUE TITLE
Change to Guidance in Building Directives

### ISSUE THREAD

**Issue by andrewconnell** [ngOfficeUIFabric/ng-officeuifabric#42]
After a healthy discussion in our Slack group, we've decided to make a few changes early on before we have too many directives built. These changes are going to be implemented immediately before we have our first release of the library. The motivation behind these changes are for following what the Angular team is doing, making it easier to build & consume directives & following general guidance.

I am going to work on updating the build process & also updating / adding docs along the lines of "building my first directive" as part of this process...
## (1) Author only in TypeScript

All directives, tests & examples will be authored in TypeScript. Examples can also be implemented using JavaScript (ES5 / ES6). 

_WHY?_ - We really need to standardize on one language and not have a collection of directives written in different languages.
## (2) Use External Modules, **NOT** Namespaces (aka: internal modules)

All directives should be written as external modules and export themselves as a module, not exporting the actual directive.

_WHY?_ - The general consensus from the TypeScript community of late is that external modules are the way to go, even from the TypeScript authors. You can see some of the discussions by some leaders in the space [here on SO](http://stackoverflow.com/questions/30357634/how-do-i-use-namespaces-with-typescript-external-modules) & from a [leading TypeScript author here](https://www.stevefenton.co.uk/2015/05/Stop-Mixing-TypeScript-Internal-And-External-Modules/).
## (3) Use Webpack as the Module Loading System

Since we're using modules, which is the way the JavaScript world is going, we need a module loader. Plenty of options out there to address this from browserify to JSPM to Webpack. We're going with Webpack.

_WHY?_ - The Angular team has elected to use **[webpack](http://webpack.github.io)** for Angular2, so we're following their lead. It also makes it very simple for consumers of the library as there is really nothing for them to do in this space... the generated combined & minified library will have everything it needs and consumers will simply need to reference the library.

---

As part of this change, I'm also going to work on adding the following:
- updated build process that will use webpack to package up the modules
- a new doc with the "building a directive checklist" that will be used when considering a pull request for merging
- a example directive that reflects this

---

_These changes directly import those who are currently building directives (@rolandoldengarm @jigargandhi @waldekmastykarz @jjczopek)... please ensure you are respecting these changes to the ROE (rules of engagement :smile:) before submitting a PR._

> If you want to see an example of this in action, check out the changes to the **textfield** directive that @s-KaiNet did. Grab his fork (https://github.com/s-KaiNet/ng-officeuifabric), switch to the branch **ExModules** & look at the `/src/components/textfield/demoBasicUsage/index.html` to see how it works. 
> 
> The steps on your machine:

``` bash
$ git clone https://github.com/s-KaiNet/ng-officeuifabric ngfabricchanges
$ cd ngfabricchanges
$ git checkout ExModules
$ npm install
$ tsd install -ros
$ tsc -p ./
$ gulp webpack
$ open src/components/textfield/demoBasicUsage/index.html
```
## Items In This Update

The following work items as part of this update:
- [x] Update build process to use webpack
- [x] Update dev guides doc to explain use of webpack
- [x] Update test process
- [x] Remove `choicefield` and `textfield` from `master` until they are using resolved stuff
- [x] Include sample directive in repo with example
- [x] Create doc on creating angular directives checklist including
  - module naming
  - adding module to loader
  - examples
  - test
  - docs
  - external module loading

**Comment by waldekmastykarz** [comment]
Trying to run `$ gulp test` using the new ROE I'm getting the following PhantomJS error:

```
ReferenceError: Can't find variable: require
at ~/ng-officeuifabric/src/core/core.js:9
```

Transpiled core.js:

``` js
var angular = require('angular');
var tableModule = require('../components/table/tableDirective');
angular.module('fabric.ui.components', [
    tableModule.module.name
]);
```

Is there anything else that should be included in the sample?

**Comment by andrewconnell** [comment]
@waldekmastykarz I'm going to get this working first before troubleshooting other stuff... big update and need to get it done ASAP to unblock folks.Thanks for being patient here...

**Comment by waldekmastykarz** [comment]
@andrewconnell sure, let me know if I can help with anything

**Comment by andrewconnell** [comment]
The problem you were running into is that `require()` is not known by browsers as it's a ES6 thing (modules). What you need is something to wrap it up... that's one of the things webpack is doing for you. So you needed to inject webpack between karma & your tests... 

I just pushed working webpack including testing to branch **issue42-webpack** in [my fork](https://github.com/andrewconnell/ng-officeuifabric/tree/issue42-webpack). Everything is working as expected, including testing, if you want to try kicking the tires (I'll submit a PR once I have the checklist above finished as two PRs - one for the webpack + docs & one for a sample directive). 

You'll need to make tweaks to the existing files (`core.ts` & the directives, but not the specs) to see it working. There's one part that I haven't figured out yet that isn't ideal, but isn't the end of the world. When you run a test, if there's an error, you get a reference to the error line within the transpiled JavaScript file in the spec. It does map the webpack generated bundle JS file => transpiled JS file, so you don't have to weed through the webpack header code, but it doesn't map back to the typescript source line.

The challenge is there are two layers of sourcemaps: (1) `*.ts` => `*.js` and (2) `*.js` => [webpack bundled] `*.js` as when using karma there are actually two preprocessors (transpile TypeScript to JavaScript and then apply webpack. I've tried a few things but the CoffeeScript guys are also having the same issue & have been working through it for a few months. For now, I see it as a non-blocker so I'm moving on to get this stuff done so we can get back to writing directives and can make the debugging process of troubleshooting failing tests easier later.

**Comment by waldekmastykarz** [comment]
I've just tried including your changes in my fork but still can't get it to work. The error that I'm getting now is:

```
03 01 2016 14:02:57.949:WARN [preprocess]: Can not load "sourcemap", it is not registered!
  Perhaps you are missing some plugin?
ts-loader: Using typescript@1.7.3 and ~/ng-officeuifabric/tsconfig.json
03 01 2016 14:02:59.854:ERROR [karma]: [TypeError: preprocessors.shift(...) is not a function]
TypeError: preprocessors.shift(...) is not a function
    at nextPreprocessor (~/ng-officeuifabric/node_modules/karma/lib/preprocessor.js:73:28)
    at ~/ng-officeuifabric/node_modules/karma-webpack/index.js:181:4
    at MemoryFileSystem.readFile (~/ng-officeuifabric/node_modules/webpack-dev-middleware/node_modules/memory-fs/lib/MemoryFileSystem.js:301:9)
    at doRead (~/ng-officeuifabric/node_modules/karma-webpack/index.js:156:26)
    at Plugin.readFile (~/ng-officeuifabric/node_modules/karma-webpack/index.js:160:3)
    at doNTCallback0 (node.js:417:9)
    at process._tickCallback (node.js:346:13)
```

Any ideas what I might be missing? I've pushed my changes to my [fork](https://github.com/waldekmastykarz/ng-officeuifabric/tree/issue-36).

**Comment by s-KaiNet** [comment]
@waldekmastykarz , `npm install karma-sourcemap-loader --save-dev`  
@andrewconnell this dependency is missing under `package.json`

**Comment by andrewconnell** [comment]
Good catch… not sure why that didn’t get committed.

**Comment by waldekmastykarz** [comment]
w00t! Got me some failing tests. That I can fix. Thanks guys!

**Comment by andrewconnell** [comment]
Just pushed lot of doc updates to my fork, same branch. Includes a directive checklist we'll follow.

I'm waiting to submit this PR until I have a working directive that matches it (<uif-icon />).

**Comment by waldekmastykarz** [comment]
:+1:

**Comment by waldekmastykarz** [comment]
I've fixed the tests in my fork. It turns out I forgot to pass the scope to the compile function. All tests passing now. https://github.com/waldekmastykarz/ng-officeuifabric/blob/c058cdbc78479a853b454d001ed5f685944da808/src/components/table/tableDirective.spec.ts
